// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhgFXiAcDbEZMLl0uZ1CueUJ_gi5fR0YM',
    appId: '1:787391700320:web:3d41a2e247589bac055205',
    messagingSenderId: '787391700320',
    projectId: 'chatapp-76b36',
    authDomain: 'chatapp-76b36.firebaseapp.com',
    storageBucket: 'chatapp-76b36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSdhl2wdrmMgphokzsFUMblyh1Td4Rmk8',
    appId: '1:787391700320:android:bf2648fd192b6078055205',
    messagingSenderId: '787391700320',
    projectId: 'chatapp-76b36',
    storageBucket: 'chatapp-76b36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2n6Ih4Krk91kZ5w3MQ-ZvFSTwPaRNiUs',
    appId: '1:787391700320:ios:7cad7ad0ef571693055205',
    messagingSenderId: '787391700320',
    projectId: 'chatapp-76b36',
    storageBucket: 'chatapp-76b36.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2n6Ih4Krk91kZ5w3MQ-ZvFSTwPaRNiUs',
    appId: '1:787391700320:ios:43111f734d7b923b055205',
    messagingSenderId: '787391700320',
    projectId: 'chatapp-76b36',
    storageBucket: 'chatapp-76b36.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
